Added Auslöser to Fahrstraßen.
DevonFrosch/ESTW-TC pull request #6
Opened 2021-02-21 22:18 UTC by Alexander912

Added Auslöser to Fahrstraßen, so they can be triggered via Redstone.

2021-02-22 14:34 UTC, DevonFrosch requested changes

2021-02-22 14:34 UTC, DevonFrosch commented on README.md
> +		- `auslöser`
Das ist leider falsch :D Der Name unten ist `ausloeser`, und wenn ich mir das Handling von Umlauten in ComputerCraft ansehe, ist das auch besser so...

2021-02-22 14:34 UTC, DevonFrosch commented on programme/stellwerk.lua
> +                log.debug("onRedstoneChange: Fahrstrassentrigger " .. fName .. " " .. state)
Wäre hier nicht `Fahrstrassenauslöser` statt `Fahrstrassentrigger` besser? Dann ist man gleich beim richtigen Namen.

2021-03-09 13:15 UTC, Alexander912 reviewed
Ich würde den RP schließen, wenn du deinen akzeptiert hast

2021-03-09 13:15 UTC, Alexander912 commented on programme/stellwerk.lua
> +                log.debug("onRedstoneChange: Fahrstrassentrigger " .. fName .. " " .. state)
Stimmt auch, Aber hast du ja beides mit https://github.com/DevonFrosch/ESTW-TC/pull/9 schon selbst implementiert.

2021-03-09 13:15 UTC, Alexander912 commented on README.md
> +		- `auslöser`
Stimmt.

2021-03-10 12:01 UTC, DevonFrosch commented
#9 gemerged, danke trotzdem für die Idee :-)

2021-03-10 12:01 UTC, closed without merging